#!/bin/bash

ip tuntap add dev tun0 mode tun
ip link set up dev tun0
ip a add 10.0.0.1/24 dev tun0

echo 1 > /proc/sys/net/ipv4/conf/tun0/accept_local
echo 1 > /proc/sys/net/ipv4/ip_forward

echo "200 astro" > /etc/iproute2/rt_tables 

ip rule add from all lookup astro
ip route add default dev tun0 table astro
ip rule add iif tun0 lookup main priority 500

#Route responses through the TUN interface
iptables -t nat -A POSTROUTING -o tun0 -s 10.0.0.1 -j SNAT --to-source 10.0.0.2
iptables -t nat -A POSTROUTING -o enp1s0 -s 10.0.0.2 -j MASQUERADE
